%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"
# first time don't set System.LoadAtlasFromFile
System.LoadAtlasFromFile: ""
System.SaveAtlasToFile: "maps_create"

## not first time run, reuse map
# System.LoadAtlasFromFile: "maps_create"
# System.SaveAtlasToFile: "maps_update"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 602.3828350762175
Camera1.fy: 601.7834470281514
Camera1.cx: 323.05336184047354
Camera1.cy: 242.67904631390357
# distortion parameters
Camera1.k1: 0.08938769157077182
Camera1.k2: -0.18672960342873615
Camera1.p1: 0.0014334537092811352
Camera1.p2: 0.002710797970673439

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 40.0
Stereo.b: 0.0745

# Depth map values factor
RGBD.DepthMapFactor: 1000.0
UseOpticalFlow: 0
UseClahe: 1
KFInsertInterval: 0.4 #默认为0.5s
LKWindowSize: 40
MASK_THRESHOLD: 10
UseGMSInit: 1
F_THRESHOLD: 1.0
UseICP: 0
UseICPLoop: 0
UseICPLocalBA: 0
UseLidarLocalBA: 0
TimeRecentlyLost: 20.0
VoxelResolution: 0.1
UsePointCloudObs: 1
UseRobotOdom: 1
InsertKFsWhenLost: 1
DelayScale: 1
UseViewer: 1
Downsample: 3
ICPMethod: "GICP"
MaxIterations: 3
T_odom_w: !!opencv-matrix
   rows: 3
   cols: 3
   dt: f
   data: [0.0 ,-1.0,-0.0,
            0.0,-0.0,-1.0,
            1.0 ,0.0 ,-0.0]

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.99973282, -0.02190689, -0.00737457, -0.02763392,
          0.02191565,  0.99975921,  0.00110967,  0.00867528,
          0.00734848, -0.00127099,  0.99997219,  0.01926674,
          0.0,         0.0,         0.0,         1.0]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 1

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1.7671710647790388e-03  # Gyroscope Noise density
IMU.NoiseAcc: 2.1353072236411585e-02   # Accelerometer Noise density
IMU.GyroWalk: 3.16550491199378e-05     # Gyroscope Random walk
IMU.AccWalk: 0.0009564636987799425     # Accelerometer Random walk
IMU.Frequency: 200.0
IMU.IMUMethod: 0
IMU.FasterInit: 0
IMU.TimeRecentlyLost: 10.0
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000
ORBextractor.type: ORB
# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 2

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0

LidarMapping.GlobalResolution: 0.1
LidarMapping.LocalResolution: 0.1
LidarMapping.meank: 50
LidarMapping.thresh: 0.2
LidarMapping.ConfigFile: "/home/zju/navigation/GeoFlowSlam/Examples/ROS2/RGB-D-Inertial/config/lidar_d435i.yaml"